languageCode = "en"
languageName = "English"
weight = 1
title = "Joshua Hayes"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  # logo = "img/logo.png"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My personal blog"
  # copyright = "Copy, _right?_ :thinking_face:"

[author]
   name = "Joshua Hayes"
   image = "img/pfp.png"
   headline = "Software Engineer | Cat Dad"
   bio = "As a new grad software engineer working in the insurance industry, I have honed my skills in full-stack development, "
   links = [
      { email = "mailto:josh.hayes121@icloud.com" },
      { github = "https://github.com/joshuahayesvcu" },
      { linkedin = "https://linkedin.com/in/joshua-hayes-vcu" },
]
